### ISSUE TITLE
Add a <noscript> tag for people having JavaScript disabled by default

### ISSUE THREAD

**Issue by Bios-Marcel** [Southclaws/cex.watch#1]

**Comment by Southclaws** [comment]
Everything works fine apart from labels on the graph https://github.com/esnet/react-timeseries-charts/ noscript won't help here unless I rewrite the graph from scratch.

**Comment by Bios-Marcel** [comment]
The noscript tag could simply be used in order to tell the user: `Hey, we are sorry, but the Graph won't work correctly, because your browser doesn't allow/support usage of JavaScript`.
